/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `ac_windfarm` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `value` varchar(20) COLLATE utf8_spanish_ci DEFAULT NULL,
  `name` varchar(60) COLLATE utf8_spanish_ci DEFAULT NULL,
  `description` varchar(255) COLLATE utf8_spanish_ci DEFAULT NULL,
  `delegation_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_windfarm_delegation1` (`delegation_id`),
  CONSTRAINT `fk_windfarm_delegation1` FOREIGN KEY (`delegation_id`) REFERENCES `ac_delegation` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=36 DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
INSERT INTO `ac_windfarm` VALUES (1,NULL,'CORISCADA','',3),(2,NULL,'VALDEPERO','',3),(5,NULL,'Silvarredonda','123',NULL),(16,NULL,'COMPROBACION',NULL,NULL),(17,NULL,'CALUENGO',NULL,NULL),(18,NULL,'CANREDONDO',NULL,NULL),(19,NULL,'CASA',NULL,NULL),(20,NULL,'CODESAS I',NULL,NULL),(21,NULL,'CODESAS II',NULL,NULL),(22,NULL,'LA LOSILLA',NULL,NULL),(23,NULL,'LOMA GORDA',NULL,NULL),(24,NULL,'MONTEJO',NULL,NULL),(25,NULL,'PEÑA I',NULL,NULL),(26,NULL,'SAN GIL',NULL,NULL),(27,NULL,'SE 1A',NULL,NULL),(28,NULL,'SE 1B - EGASTIAGA',NULL,NULL),(29,NULL,'SE 2A - AÑORBE',NULL,NULL),(30,NULL,'SE 2B - OLCOZ',NULL,NULL),(31,NULL,'SE 2C - CARAQUIDOYA',NULL,NULL),(32,NULL,'SILVAREDONDA',NULL,NULL),(33,NULL,'UZKITA',NULL,NULL),(34,NULL,'VALDELACASA',NULL,NULL),(35,NULL,'VALDELÍN',NULL,NULL);
