/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `importar` (
  `id` int(6) NOT NULL AUTO_INCREMENT,
  `temporada` varchar(5) COLLATE utf8_spanish_ci NOT NULL DEFAULT '',
  `pedido` varchar(6) COLLATE utf8_spanish_ci NOT NULL DEFAULT '',
  `ref_pedido` varchar(6) COLLATE utf8_spanish_ci NOT NULL DEFAULT '',
  `articulo` varchar(6) COLLATE utf8_spanish_ci NOT NULL DEFAULT '',
  `ref_articulo` varchar(7) COLLATE utf8_spanish_ci NOT NULL DEFAULT '',
  `descripcion` varchar(40) COLLATE utf8_spanish_ci NOT NULL DEFAULT '',
  `cliente` varchar(20) COLLATE utf8_spanish_ci NOT NULL DEFAULT '',
  `seccion` varchar(20) COLLATE utf8_spanish_ci NOT NULL DEFAULT '',
  `idcolor` int(3) NOT NULL DEFAULT '0',
  `talla1` varchar(3) CHARACTER SET utf8 NOT NULL DEFAULT '',
  `codigo1` varchar(14) CHARACTER SET utf8 NOT NULL DEFAULT '',
  `texto1` varchar(24) COLLATE utf8_spanish_ci NOT NULL DEFAULT '',
  `talla2` varchar(3) CHARACTER SET utf8 NOT NULL DEFAULT '',
  `codigo2` varchar(14) CHARACTER SET utf8 NOT NULL DEFAULT '',
  `texto2` varchar(24) COLLATE utf8_spanish_ci NOT NULL DEFAULT '',
  `talla3` varchar(3) CHARACTER SET utf8 NOT NULL DEFAULT '',
  `codigo3` varchar(14) CHARACTER SET utf8 NOT NULL DEFAULT '',
  `texto3` varchar(24) COLLATE utf8_spanish_ci NOT NULL DEFAULT '',
  `talla4` varchar(3) CHARACTER SET utf8 NOT NULL DEFAULT '',
  `codigo4` varchar(14) CHARACTER SET utf8 NOT NULL DEFAULT '',
  `texto4` varchar(24) COLLATE utf8_spanish_ci NOT NULL DEFAULT '',
  `talla5` varchar(3) CHARACTER SET utf8 NOT NULL DEFAULT '',
  `codigo5` varchar(14) CHARACTER SET utf8 NOT NULL DEFAULT '',
  `texto5` varchar(24) COLLATE utf8_spanish_ci NOT NULL DEFAULT '',
  `talla6` varchar(3) CHARACTER SET utf8 NOT NULL DEFAULT '',
  `codigo6` varchar(14) CHARACTER SET utf8 NOT NULL DEFAULT '',
  `texto6` varchar(24) COLLATE utf8_spanish_ci NOT NULL DEFAULT '',
  `talla7` varchar(3) CHARACTER SET utf8 NOT NULL DEFAULT '',
  `codigo7` varchar(14) CHARACTER SET utf8 NOT NULL DEFAULT '',
  `texto7` varchar(24) COLLATE utf8_spanish_ci NOT NULL DEFAULT '',
  `talla8` varchar(3) CHARACTER SET utf8 NOT NULL DEFAULT '',
  `codigo8` varchar(18) CHARACTER SET utf8 NOT NULL DEFAULT '',
  `texto8` varchar(24) COLLATE utf8_spanish_ci NOT NULL DEFAULT '',
  `quit` varchar(3) COLLATE utf8_spanish_ci NOT NULL DEFAULT '',
  `fabricacion` varchar(20) COLLATE utf8_spanish_ci NOT NULL DEFAULT '',
  `destino` varchar(20) COLLATE utf8_spanish_ci NOT NULL DEFAULT '',
  `idlavado` varchar(2) COLLATE utf8_spanish_ci NOT NULL DEFAULT '',
  `precio` varchar(6) COLLATE utf8_spanish_ci NOT NULL DEFAULT '',
  `precio2` varchar(6) COLLATE utf8_spanish_ci NOT NULL DEFAULT '',
  `precio3` varchar(6) COLLATE utf8_spanish_ci NOT NULL DEFAULT '',
  `precio4` varchar(6) COLLATE utf8_spanish_ci NOT NULL,
  `precio5` varchar(6) COLLATE utf8_spanish_ci NOT NULL,
  `tallas` varchar(35) CHARACTER SET utf8 NOT NULL DEFAULT '',
  `composicion` varchar(72) COLLATE utf8_spanish_ci NOT NULL DEFAULT '',
  `idproveedor` int(5) NOT NULL DEFAULT '0',
  `proveedor` varchar(50) COLLATE utf8_spanish_ci NOT NULL DEFAULT '',
  `pack1` int(2) NOT NULL DEFAULT '0',
  `pack2` int(2) NOT NULL DEFAULT '0',
  `pack3` int(2) NOT NULL DEFAULT '0',
  `pack4` int(2) NOT NULL DEFAULT '0',
  `pack5` int(2) NOT NULL DEFAULT '0',
  `pack6` int(2) NOT NULL DEFAULT '0',
  `pack7` int(2) NOT NULL DEFAULT '0',
  `pack8` int(2) NOT NULL DEFAULT '0',
  `colorpack` varchar(3) COLLATE utf8_spanish_ci NOT NULL DEFAULT '',
  `lotes` int(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `temporada` (`temporada`),
  KEY `idcolor` (`idcolor`),
  KEY `idlavado` (`idlavado`),
  KEY `pedido` (`pedido`),
  KEY `codigo1` (`codigo1`),
  KEY `codigo2` (`codigo2`),
  KEY `codigo3` (`codigo3`),
  KEY `codigo4` (`codigo4`),
  KEY `codigo5` (`codigo5`),
  KEY `codigo6` (`codigo6`),
  KEY `codigo7` (`codigo7`),
  KEY `codigo8` (`codigo8`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
