/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `user_preferences` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL DEFAULT '0',
  `others` text,
  `hide_mail` tinyint(1) DEFAULT '0',
  `time_zone` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `index_user_preferences_on_user_id` (`user_id`)
) ENGINE=InnoDB AUTO_INCREMENT=17 DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;
INSERT INTO `user_preferences` VALUES (1,2,'--- {}\n\n',0,NULL),(2,1,'--- \n:comments_sorting: asc\n:gantt_zoom: 2\n:gantt_months: 6\n:my_page_layout: \n  left: []\n\n  top: \n  - issuesassignedtome\n  - calendar\n  - news\n  - issueswatched\n  right: []\n\n:no_self_notified: true\n',0,'Madrid'),(3,3,'--- \n:gantt_zoom: 2\n:my_page_layout: \n  left: \n  - issueswatched\n  - documents\n  - news\n  right: \n  - issuesreportedbyme\n  - calendar\n  top: \n  - issuesassignedtome\n  - timelog\n:gantt_months: 6\n',0,NULL),(4,4,'--- \n:gantt_zoom: 2\n:gantt_months: 6\n:my_page_layout: \n  left: \n  - timelog\n  right: \n  - issuesreportedbyme\n  - news\n  top: \n  - issueswatched\n  - issuesassignedtome\n  - calendar\n',0,NULL),(5,5,'--- \n:gantt_months: 6\n:my_page_layout: \n  left: \n  - timelog\n  right: \n  - news\n  top: \n  - issuesassignedtome\n  - calendar\n:gantt_zoom: 2\n',0,NULL),(6,6,'--- \n:comments_sorting: asc\n:gantt_zoom: 2\n:my_page_layout: \n  left: \n  - news\n  right: \n  - timelog\n  top: \n  - issuesassignedtome\n  - calendar\n:gantt_months: 6\n:no_self_notified: false\n',0,''),(7,7,'--- \n:my_page_layout: \n  left: \n  - issuesassignedtome\n  top: \n  - timelog\n  - calendar\n  right: \n  - news\n',0,NULL),(8,10,'--- \n:gantt_months: 6\n:my_page_layout: \n  left: \n  - timelog\n  - issuesassignedtome\n  right: \n  - issuesreportedbyme\n  - news\n  top: \n  - calendar\n:no_self_notified: false\n:gantt_zoom: 4\n:comments_sorting: asc\n',0,''),(9,11,'--- \n:gantt_zoom: 4\n:my_page_layout: \n  left: []\n\n  top: \n  - timelog\n  - calendar\n  right: []\n\n:gantt_months: 1\n',0,NULL),(10,12,'--- {}\n\n',0,NULL),(11,15,'--- \n:my_page_layout: \n  left: \n  - documents\n  - timelog\n  right: \n  - issuesassignedtome\n  - news\n  top: \n  - calendar\n',0,NULL),(12,17,'--- \n:gantt_zoom: 2\n:gantt_months: 6\n',0,NULL),(13,18,'--- \n:my_page_layout: \n  left: []\n\n  top: \n  - timelog\n  - calendar\n  - documents\n  - news\n  right: []\n\n',0,NULL),(14,19,'--- \n:comments_sorting: asc\n:gantt_zoom: 2\n:gantt_months: 6\n:my_page_layout: \n  left: []\n\n  top: \n  - issuesassignedtome\n  - timelog\n  - calendar\n  - documents\n  right: []\n\n:no_self_notified: false\n',0,''),(15,20,'--- {}\n\n',0,NULL),(16,22,'--- \n:gantt_zoom: 2\n:gantt_months: 6\n',0,NULL);
