/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `gi_incidence_type` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `type` varchar(160) COLLATE utf8_spanish_ci DEFAULT NULL,
  `incidence_clasification_id` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_incidence_type_incidence_clasification1` (`incidence_clasification_id`)
) ENGINE=InnoDB AUTO_INCREMENT=118 DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
INSERT INTO `gi_incidence_type` VALUES (2,'Modif Revisión Plano - Realizado No Siguiendo lo indicado debido a Interferencia con otro gremio o fallo diseño',3),(8,'Modif Revisión Plano - Realizado No Siguiendo lo indicado debido a Interferencia con otro gremio.',2),(9,'Modif Revisión Plano - Realizado No Siguiendo lo indicado debido a \'Otra\'(Especificar)',2),(10,'Modif Revisión Plano - Retrabajo siguiendo el plano debido a interferencias con otros gremios',2),(11,'Modif Revisión Plano - Retrabajo siguiendo el plano debido a \'Otra\' (Especificar)',2),(12,'Fallo interno ElectroRayma (Especificar)',2),(14,'Modificaciones por revisión de plano',4),(15,'Retrabajo realizado NO siguiendo lo indicado en el plano',4),(16,'Retrabajo siguiendo el plano en vigor',4),(17,'Fallo interno ElectroRayma (Especificar)',4),(18,'Modif Revisión Plano - Realizado No Siguiendo lo indicado debido a reubicación de equipo por fallo de diseño',3),(19,'Modif Revisión Plano - Realizado No Siguiendo lo indicado debido a \'Otra\'(Especificar)',3),(20,'Modif Revisión Plano - Retrabajo siguiendo el plano debido a Interferencia con otro gremio',3),(21,'Modif Revisión Plano - Retrabajo siguiendo el plano debido a cambio equipos dañados/averiados/reformas',3),(22,'Modif Revisión Plano - Retrabajo siguiendo el plano debido a cambio situación equipos pruebas',3),(23,'Modif Revisión Plano - Retrabajo siguiendo el plano debido a \'Otra\' (Especificar)',3),(24,'Fallo interno ElectroRayma (Especificar)',3),(25,'Modif Revisión Plano - Realizado No Siguiendo lo indicado debido a errores en hojas de conexionado por fallo de diseño',5),(26,'Modif Revisión Plano - Realizado No Siguiendo lo indicado debido a falta de información (Hojas conexionado en blanco)',5),(27,'Modif Revisión Plano - Realizado No Siguiendo lo indicado debido a modif. por pruebas',5),(28,'Modif Revisión Plano - Retrabajo siguiendo el plano debido a interferencias con otros gremios',5),(29,'Modif Revisión Plano - Retrabajo siguiendo el plano debido a reubicación equipo por fallo de diseño',5),(30,'Modif Revisión Plano - Retrabajo siguiendo el plano debido a cables dañados, rotos o cambio',5),(31,'Modif Revisión Plano - Retrabajo siguiendo el plano debido a \'Otra\' (Especificar)',5),(32,'Fallo interno ElectroRayma (Especificar)',5),(113,'Otra',1),(114,'Otra',2),(115,'Otra',3),(116,'Otra',4),(117,'Otra',5);
