/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `gie_cable` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `codigo` varchar(45) CHARACTER SET utf8 DEFAULT '0',
  `cod_militar` varchar(45) CHARACTER SET utf8 DEFAULT '0',
  `copic` varchar(45) CHARACTER SET utf8 DEFAULT '0',
  `tipo_cable` varchar(45) CHARACTER SET utf8 DEFAULT '0',
  `f_crea` varchar(20) CHARACTER SET utf8 DEFAULT '0',
  `f_mod` varchar(20) CHARACTER SET utf8 DEFAULT '0',
  `especificacion` varchar(45) CHARACTER SET utf8 DEFAULT '0',
  `seccion` varchar(20) CHARACTER SET utf8 DEFAULT '0',
  `plano` varchar(20) CHARACTER SET utf8 DEFAULT '0',
  `rutado` varchar(1) CHARACTER SET utf8 DEFAULT '0',
  `long_rut` varchar(20) CHARACTER SET utf8 DEFAULT '0',
  `origen` varchar(100) CHARACTER SET utf8 DEFAULT '0',
  `destino` varchar(100) CHARACTER SET utf8 DEFAULT '0',
  `des_ori` varchar(200) CHARACTER SET utf8 DEFAULT '0',
  `des_des` varchar(200) CHARACTER SET utf8 DEFAULT '0',
  `aprob_tend` varchar(1) CHARACTER SET utf8 DEFAULT '0',
  `f_aprob_tend` varchar(20) CHARACTER SET utf8 DEFAULT '0',
  `aprob_conex` varchar(1) CHARACTER SET utf8 DEFAULT '0',
  `f_aprob_conex` varchar(20) CHARACTER SET utf8 DEFAULT '0',
  `bobina` varchar(45) CHARACTER SET utf8 DEFAULT '0',
  `ot_tendido` varchar(45) CHARACTER SET utf8 DEFAULT '0',
  `empresa` varchar(100) CHARACTER SET utf8 DEFAULT '0',
  `f_tendido` varchar(20) CHARACTER SET utf8 DEFAULT '0',
  `ot_conex_ori` varchar(45) CHARACTER SET utf8 DEFAULT '0',
  `f_conex_ori` varchar(20) CHARACTER SET utf8 DEFAULT '0',
  `emp_conex_ori` varchar(100) CHARACTER SET utf8 DEFAULT '0',
  `ot_conex_des` varchar(45) CHARACTER SET utf8 DEFAULT '0',
  `f_conex_des` varchar(20) CHARACTER SET utf8 DEFAULT '0',
  `emp_conex_des` varchar(100) CHARACTER SET utf8 DEFAULT '0',
  `corte` varchar(1) CHARACTER SET utf8 DEFAULT '0',
  `f_corte` varchar(20) CHARACTER SET utf8 DEFAULT '0',
  `long_corte` varchar(10) CHARACTER SET utf8 DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `ix_codigo` (`codigo`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
