/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `seccion` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `nombre` varchar(75) CHARACTER SET utf8 NOT NULL,
  `descripcion` varchar(105) CHARACTER SET utf8 NOT NULL,
  `padre_id` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=28 DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
INSERT INTO `seccion` VALUES (1,'Clientes','Visualización del listado de clientes',0),(2,'Obras','Visualización del listado de obras',0),(3,'Importacion Telematel','Importacion de archivos excel de telematel',0),(4,'Importacion Obras','Importación de archivos excel para obras',0),(5,'Detalle de Obra','Dialogo de edición de obras',2),(6,'Seguimiento','Seguimientos de las obras',5),(7,'Valores Economicos','Valores Económicos de las obras',5),(8,'Facturacion','Facturación de las obras',5),(9,'Supervision','Supervisión de las obras',5),(10,'Proveedores','Visualización del listado de proveedores',0),(11,'Incidencias','Incidencias de proveedores',18),(12,'Pedidos','Pedidos de proveedores',18),(13,'Exportacion de Obras','Exportacion de obras',0),(14,'Usuarios','Administración usuarios',0),(15,'Empleados','Administración empleados',0),(16,'Exportacion Seguimiento','Exportacion seguimiento',0),(17,'Perfiles','Administración de perfiles y permisos',0),(18,'Detalle de Proveedor','Dialogo de edición de proveedores',10),(19,'Resumen Anual Incidencias','Exportación Resumen anual de incidencias',0),(20,'Resumen Incidencias','Exportación resumen periódico de incidencias',0),(21,'Informe Incidencias','Exportación informe periódico de incidencias',0),(22,'Grafica Avance Obras','Pantalla de muestra del grafico de avance de obras',5),(23,'Prevision Facturacion','Pantalla de muestra del grafico de prevision de facturacion',0),(24,'Avance Mensual','Pantalla de muestra del indicador de avance mensual',0),(25,'Exportacion Administracion','Exportacion de informe de seguimientos.',0),(26,'Hitos Administracion','Pestaña de adminstración de hitos para administración.',0),(27,'Informe Cambios Facturacion','Pestaña de muestra del informe de cambios procedente de telematel',0);
